# Generated by Django 5.0.7 on 2024-07-13 09:48

import clickhouse_backend.models
import django.db.models.manager
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', clickhouse_backend.models.Int32Field()),
                ('product_id', clickhouse_backend.models.Int32Field()),
                ('amount', clickhouse_backend.models.Float32Field()),
                ('timestamp', clickhouse_backend.models.DateTime64Field(default=django.utils.timezone.now)),
            ],
            options={
                'ordering': ['-timestamp'],
                'engine': clickhouse_backend.models.MergeTree(enable_mixed_granularity_parts=1, index_granularity=1024, index_granularity_bytes=1048576, order_by=('timestamp', 'user_id'), partition_by=clickhouse_backend.models.toYYYYMMDD('timestamp'), primary_key='timestamp'),
            },
            managers=[
                ('objects', django.db.models.manager.Manager()),
                ('_overwrite_base_manager', django.db.models.manager.Manager()),
            ],
        ),
    ]
